### ISSUE TITLE
automatically variable cannot create in 3.1

### ISSUE THREAD

**Issue by panchaldixit** [erikwett/qsVariable#10]
i cannot create automatically variable using qsvarible extension but it work fine after manually making variable..

**Comment by pgeiss619** [comment]
How do you manually make a variable to reference the qsvariable? I know how to create variables but can't figure out how to make it the qsvariable

**Comment by panchaldixit** [comment]
Hello,
You make one variable and same name use in qsvarible extension. it would be work.

Regards,
Dixit Panchal.

**Comment by bobocharbo** [comment]
Same issue for me. 
I even noticed a really strange thing : 

-  I create a variable with the variable manager in Qlik Sense (let's say 'vNbMonths')
- I assign an expression value (=3) and save the variable.
- I create the qsVariable object and name the variable as 'NbMonths'  (the same name as before)
-  I create 3 or 4 alternatives and I can now change the value of the variable.
-  I can see changes are effective with a Text and Image object, i.e the display value changes when I change the variable value
- But when I go back to the variable manager, the value is still 3 (even if the Text and Image displays the good value !!)

**Comment by gameoverzx** [comment]
Hi,

Any idea how to go about using this?
Is it supposed to automatically save the name i gave for it as a measure?
If so, i am unable to do so.

Thanks

**Comment by panchaldixit** [comment]
You can create manually same name as you are using in mesure.

Regards,
Dixit Panchal

**Comment by erikwett** [comment]
Verified this in Qlik Sense June 2017, and it seems to work fine. Planning to remove this feature anyway, as there now is a dialog for creating variables, with the possibility to set initial value.
