### ISSUE TITLE
Slow or no response to selections QS 3.1.3

### ISSUE THREAD

**Issue by PetravanderHoek** [erikwett/qsVariable#13]
I use the qsvariable extension to switch between measures in a graph and keep the same sorting. The values in my qsvariable are again expressions in variable list. When I make a selection in Qlik Sense, the graph doesn't respond or responds very slow. Most of the times I first have to switch between the different values in my qsvariable before I get the results adjusted to the selection. Is this a known issue?

**Comment by erikwett** [comment]
Not this is not a known issue are probably is not because of the extension but because your expressions take time to evaluate.
