### ISSUE TITLE
issues when upgrading to 3.2

### ISSUE THREAD

**Issue by jarm001** [erikwett/qsVariable#20]
Hi 

Now that I have upgraded to 3.2 Qlik sense, my variable won't work. I have tried downloading the latest version of Qlik sense variable extension but it hasn't seemed to fix anything. 

please either give me a link to the correct latest version or give me some guidance on what to do next? 

Thanks in advance

**Comment by erikwett** [comment]
Make sure you clear the browser cache and then verify again.
