### ISSUE TITLE
SR 3.2 SR4 variable Issue

### ISSUE THREAD

**Issue by PakchangKyu** [erikwett/qsVariable#21]
I have upgraded to 3.2 SR4 Qlik Sense, but my variable didn't work. 
So I downloaded your latest variable zip. but it didn't still work

Please give me some guidance on what to do

**Comment by erikwett** [comment]
There are wellness known bugs in Qlik Sense 3.2 SR3 and SR4. The latest version container a workaround for this so it should work. If you still have problems:
- clear your browser cache and try again
- if it still does not work, downgrade to SR2
