### ISSUE TITLE
Variables not being updated

### ISSUE THREAD

**Issue by DaltonRuer** [erikwett/qsVariable#25]
I've used the variable extension for a long time. I'm using June 2017 release and latest qsvariable code but after I leave the field the value reverts back to the original value for some reason.

**Comment by paulyeo11** [comment]
I also face with the same issue. Hope that when the variable is updated , pls inform me.

**Comment by erikwett** [comment]
Download Qlik Sense June 2017 desktop and verified the extension. Seems to work when I try it. Could you be a bit more specific: 
- server or desktop install??
- are you using buttons, input field, slider ...
- have you made sure the browser cache is cleared?
- are there any errors in the browser console

**Comment by paulyeo11** [comment]
Hi Erik
I just test it work fine , sorry give you wrong info.
		

		Paul Yeo
DIrector
TDS Technology (S) P/L
Whatsapp +65 9326 1804
	_____________________________

**Comment by erikwett** [comment]
Cannot reproduce this problem

**Comment by paulyeo11** [comment]
Thank you very much for your contribution , it work fine now .
		

		Paul Yeo
DIrector
TDS Technology (S) P/L
Whatsapp +65 9326 1804
	





On Tue, Jul 4, 2017 at 3:05 PM +0700, "Erik Wetterberg" <notifications@github.com> wrote:












Cannot reproduce this problem

**Comment by DaltonRuer** [comment]
Pulled again. Ran and it failed.

Ran it in Desktop and it worked like a champ.

Ran server via Internet Explorer and it worked. Ran again in Chrome and it worked.

I’m working on all fronts now. Problem was obviously at my end.

Dalton Ruer
Healthcare Senior Solutions Architect
Mobile: +1 678-943-0064
Skype: QlikDork
Email:  Dalton.Ruer@qlik.com<mailto:Dalton.Ruer@qlik.com>
Blog: QlikDork.com - Latest post is The World IS Flat<http://qlikdork.com/2017/04/the-world-is-flat/>
Twitter: @QlikDork
qlik.com<http://www.qlik.com/>
The information transmitted is intended only for the person or entity to which it is addressed and may contain confidential and/or privileged material. Any review, retransmission, dissemination or other use of, or taking of any action in reliance upon, this information by persons or entities other than the intended recipient is prohibited. If you received this in error, please contact the sender and delete the material from any computer.

**Comment by erikwett** [comment]
Sounds like the old version was cached or something.

Erik

**Comment by DaltonRuer** [comment]
That’s all I can think. I’ve seen stranger with Chrome before.

Sorry to have bugged you about this. It works like a champ now.

Also be aware for your own information that a lot of times variables are used and then RELOADS are done. If a Partial Reload is done and it fails the system will roll back to the previous data and also replaces the variable. I discovered that after getting the variable to stick and I had a section in my load script that wasn’t working properly for a Partial Reload.

Dalton Ruer
Healthcare Senior Solutions Architect
Mobile: +1 678-943-0064
Skype: QlikDork
Email:  Dalton.Ruer@qlik.com<mailto:Dalton.Ruer@qlik.com>
Blog: QlikDork.com - Latest post is The World IS Flat<http://qlikdork.com/2017/04/the-world-is-flat/>
Twitter: @QlikDork
qlik.com<http://www.qlik.com/>
The information transmitted is intended only for the person or entity to which it is addressed and may contain confidential and/or privileged material. Any review, retransmission, dissemination or other use of, or taking of any action in reliance upon, this information by persons or entities other than the intended recipient is prohibited. If you received this in error, please contact the sender and delete the material from any computer.
