### ISSUE TITLE
Need to save and refresh app when adding variables

### ISSUE THREAD

**Issue by everythingiswrong** [erikwett/qsVariable#27]
Since upgrading Qlik Sense to June 2017 and using the latest version of this extension, in order for newly created variables to be usable (i.e. Selectable from the drop-down menu) with the extension, the app needs to be saved and refreshed (e.g. using F5)

This was not previously an issue (variables would be usable immediately after creation by typing the name in)

**Comment by erikwett** [comment]
Fixed in version 3.0.3: save and refresh no longer needed. You still need to trigger revalidation of the dropdown, for example by selecting another field in the property panel and then th varaible dropdown again. Probably cannot be fixed.
