### ISSUE TITLE
Extension not working on Qlik Sense Server

### ISSUE THREAD

**Issue by makrawal** [erikwett/qsVariable#28]
Hi,
This extension is working fine in Qlik Sense Desktop but not working in Qlik Sense Server. Specifically its select option. I want to use it for selecting different field in Dimension in a bar chart.
1st image is of Qlik sense desktop.
2nd image of Qlik Sense Server.
![1](https://user-images.githubusercontent.com/15025950/28321970-5dd295f2-6bf2-11e7-8c36-82e708e10f75.PNG)
![2](https://user-images.githubusercontent.com/15025950/28321976-64666100-6bf2-11e7-9e15-2bf93e921ca3.PNG)

.

**Comment by erikwett** [comment]
What version och Qlik Sense is your server running? Noterade that for 3.2 SR3 and 4 you need the older version och the extension with a workaround for a bug in those versions.

**Comment by erikwett** [comment]
Closed because no feedback from reporter
