### ISSUE TITLE
Does not work in QS 3.2 SR5 (September 2017 Release)

### ISSUE THREAD

**Issue by rhein** [erikwett/qsVariable#30]
On a recent install of Qlik Sense Server (3.2 SR5 September Release) this does not work anymore.

2 Fixes are needed in variable.js:

Reference to the current app needs to be called without any parameter, such as:
e.currApp(p) needs to be changed into e.currApp() 
setContent() is deprecated, should be changed into setStringValue()

After those changes it does work again on this version, but I can not test compatibility with earlier versions of QS or Sense Desktop.

Also using e.currApp(this) does work; however I am not sure why assigning 
`var p = this;` 
does not work (in line 314) and also if this reference is really needed anyway. For me it seems to work ok in both ways.

**Comment by erikwett** [comment]
This is a well-known Qlik Sense bug. Use the older version (2.3.1) which includes a fix for this, or better still upgrade to a Qlik Sense version without the bug.

Verfied that the extension works with Qlik Sense September 2017 (which is not QS 3.2 SR5).
