### ISSUE TITLE
qsVariable v 4, no Variable Name selection

### ISSUE THREAD

**Issue by ninjasoft2** [erikwett/qsVariable#32]
Wondering if it's my extension install, but I can't seem to give the variable a name, am I missing something ? How do assign a variable name with this extension?

**Comment by erikwett** [comment]
You can no longer create variables with the extension. You can create variables in the script (which I would recommend) or in the variable dialog. This also allows you to give them a default value.

In the property panel there is a dropdown that allows you to select one of the existing variables to use:
![image](https://user-images.githubusercontent.com/2550331/33978097-49db2bce-e09e-11e7-9722-6a241b6f1dde.png)

**Comment by ninjasoft2** [comment]
The install of version 4 on mine does not show the selection Name - https://www.dropbox.com/s/y9hrxogtwi75wh4/Capture.JPG?dl=0

**Comment by erikwett** [comment]
What Qlik Sense version are you using??

**Comment by ninjasoft2** [comment]
I’m using the latest Server version – this is what I see with version 4. Same thing occurs in the Desktop version. Funny thought, when I go back to 3.2, I can see the Name selection, but it does not change the variable.

**Comment by ninjasoft2** [comment]
I don’t see that with version 4. This is what I see. I’m creating the variable in the load file

**Comment by erikwett** [comment]
By the latest version you mean November 2017??

**Comment by ninjasoft2** [comment]
3.2 SR 3

**Comment by ninjasoft2** [comment]
On the desktop 3.2 SR 3 , but it reacts the same on the server, with I think is probably the same release 

 

From: michael.ricciardi@domenix.com [mailto:michael.ricciardi@domenix.com] 
Sent: Thursday, December 14, 2017 9:55 AM
To: 'erikwett/qsVariable' <reply@reply.github.com>; 'erikwett/qsVariable' <qsVariable@noreply.github.com>
Cc: 'ninjasoft2' <michael.ricciardi@reltechinc.com>; 'Author' <author@noreply.github.com>
Subject: RE: [erikwett/qsVariable] qsVariable v 4, no Variable Name selection (#32)

 

3.2 SR 3

**Comment by erikwett** [comment]
OK, that's actually a pretty old version. You should use the 2.3.1 version of the extension:
https://github.com/erikwett/qsVariable/releases/tag/2.3.1

**Comment by ninjasoft2** [comment]
So what version is the master ?
