### ISSUE TITLE
Latest version on QS 2018 Feb

### ISSUE THREAD

**Issue by PeterVanOers** [erikwett/qsVariable#44]
The latest version doesn't seems to work on the QS 2018 Feb release. The spinning wheel keeps on turning.
<img width="186" alt="qsvariable - qlik sense 2018 feb" src="https://user-images.githubusercontent.com/37449405/37529510-a5ddc652-2937-11e8-963c-413d1041f7b4.png">

**Comment by erikwett** [comment]
Fixed in version 5.1.2
