### ISSUE TITLE
The distribution zip is missing variable.js

### ISSUE THREAD

**Issue by dmitrygudkov** [erikwett/qsVariable#45]
It contains only .qext and its size is only 1KB. Probably, the build script didn't work properly.

**Comment by dmitrygudkov** [comment]
Adding it manually doesn't help either. Console shows: Uncaught SyntaxError: Unexpected token <

**Comment by dmitrygudkov** [comment]
Ended up using this commit: https://github.com/erikwett/qsVariable/blob/2336f25ca0c444adb7671b79d7e95381277fe9d1/dist/variable.zip

**Comment by erikwett** [comment]
Should be OK now

**Comment by dmitrygudkov** [comment]
It works now. Thank you for the super-fast resolution :)

Very well made extension. Appreciate your work @erikwett  !
