### ISSUE TITLE
Thin-Header toggled

### ISSUE THREAD

**Issue by ganyfml** [erikwett/qsVariable#49]
I like the thin-header idea. But I do not understand why the class need to be toggled.

Before I click any button:
![image](https://user-images.githubusercontent.com/9390466/38773247-b6ac4a40-4015-11e8-9c79-4dca44db8721.png)

After I click any button:
![image](https://user-images.githubusercontent.com/9390466/38773253-cb2c6a72-4015-11e8-99e0-5f568f5771ef.png)

Should it just be:
`r.closest(".qv-object-variable").addClass("thin-header", u.thinHeader)`
instead of
`r.closest(".qv-object-variable").toggleClass("thin-header", u.thinHeader)` ?

My Qlik Sense version: 11.24.1
qsVariable version: 5.2.1

Thank you!

**Comment by erikwett** [comment]
Thanks for the bug report. Noew solved in 5.2.2.
