### ISSUE TITLE
Gulp build fails

### ISSUE THREAD

**Issue by julmot** [erikwett/qsVariable#51]
```bash
requirejs task failed {"originalError":{"errno":-4058,"code":"ENOENT","syscall":"open","path":"P:\\zurich\\qlik\\extensions\\zurich-variable\\src\\style.js","fileName":"P:/zurich/qlik/extensions/zurich-variable/src/style.js","moduleTree":["variable"]}}
```

In variable.js you're depending on:

```js
define(['qlik', './util', './properties', './style']
```

whereas there does no style.js exist, only style.less.

**Comment by erikwett** [comment]
style.js is created by gulp task less. Does that task fail in your
installation??

2018-04-18 8:19 GMT+02:00 Julian Kühnel <notifications@github.com>:

**Comment by julmot** [comment]
You're right, it works. I haven't read through the entire build file. I would expect a  `CONTRIBUTING.md` with the necessary steps.
