### ISSUE TITLE
Extension unresponsive QS 3.2 SR5

### ISSUE THREAD

**Issue by prassinoux** [erikwett/qsVariable#54]
We recently upgraded from Qlik Sense 3.0 to 3.2 SR5 (yes, we are way behind ...), and this extension stopped working correctly.  After the upgrade, when I click the buttons rendered by the extension, nothing happens.  Any idea how to fix this?

![image](https://user-images.githubusercontent.com/39031041/39675384-5679d628-510f-11e8-8eda-b1a87fdcdefe.png)

In this image, I clicked "Line" - it does not turn green or modify any visualizations using the variable in the app.

Thanks for any help

**Comment by erikwett** [comment]
Hi,
There is a well-known bug in 3.2 that breaks this extension. You could use the extension version 2.3.1 found here:
https://github.com/erikwett/qsVariable/tree/Version2.3.1/dist

Or use a leter Qlik Sense version where this is fixed

**Comment by prassinoux** [comment]
Thanks – if we upgrade to a newer version will that fix it (planned for Feb 2018)?

Best regards

- Pascal

**Comment by prassinoux** [comment]
Thanks, appreciate the support!

- Pascal
