### ISSUE TITLE
Default Selection

### ISSUE THREAD

**Issue by NYamaguchi415** [erikwett/qsVariable#7]
Is there a specific way to set a default selection in dropdown or buttons? For some reason when I refresh the application the values all default to null. 

On a separate application the values are defaulting to a value and I want to change it somehow.

Thanks,
Naoki

**Comment by soeshark** [comment]
Set the start value of the variables on script.

**Comment by NYamaguchi415** [comment]
Hey @soeshark , thanks for responding. Could you clarify a bit? I'm new to Qlik and am not sure where I would script this. Thanks!

**Comment by panchaldixit** [comment]
hi NYamaguchi415
for default selection variable give one default input value of selection things 

for example i make vDemo variable then i goto variable list and find my extension and give default value in extension..
regards 
dixit

**Comment by PetravanderHoek** [comment]
I am trying the same when using calculations in variables which again I use in the qsvariable. However, it doesn't take my value in the variable list as default. Any ideas?

**Comment by panchaldixit** [comment]
You have add new variable in qliksense after added new qliksense variable
you can same variable use extension.its would be work..

**Comment by erikwett** [comment]
Set the default value in the script or in the create variable dialog
